In [4]:
import numpy as np
import matplotlib.pyplot as  plt
import pandas as pd


In [9]:
dataset=pd.read_csv("/content/food_coded.csv")
X=dataset.iloc[:, :-1].values
y=dataset.iloc[:, -1].values

In [10]:
print(X)

[['2.4' 2 1 ... 5 1 1315]
 ['3.654' 1 1 ... 4 2 900]
 ['3.3' 1 1 ... 5 1 900]
 ...
 ['3.882' 1 1 ... 4 2 1315]
 ['3' 2 1 ... 3 1 1315]
 ['3.9' 1 1 ... 4 2 575]]


In [11]:
print(y)

['187' '155' "I'm not answering this. " 'Not sure, 240' '190' '190' '180'
 '137' '180' '125' '116' '110' '264' '123' '185' '180' '145' '170' '135'
 '165' '175' '195' '185' '185' '105' '125' '160' '175' '180' '167' '115'
 '205' nan '128' '150' '150' '150' '170' '150' '175' '140' '120' '135'
 '100' '170' '113' '168' '145' '155' '150' '169' '185' '200' '265' '165'
 '192' '175' '140' '155' '155' '135' '118' '210' '180' '140' '112' '125'
 '144 lbs' '145' '130' '140' '140' '140' '200' nan '120' '150' '200' '135'
 '145' '130' '190' '170' '127' '167' '140' '190' '155' '175' '129' '260'
 '135' '190' '165' '175' '184' '210' '155' '185' '165' '125' '160' '135'
 '130' '230' '125' '130' '165' '128' '200' '160' '170' '129' '170' '138'
 '150' '170' '113' '140' '185' '156' '180' '120' '135' '135']


In [14]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(x[:,1:3])
X[:,1:3]=imputer.transform(X[:,1:3])

In [15]:
print(X)

[['2.4' 2.0 1.0 ... 5 1 1315]
 ['3.654' 1.0 1.0 ... 4 2 900]
 ['3.3' 1.0 1.0 ... 5 1 900]
 ...
 ['3.882' 1.0 1.0 ... 4 2 1315]
 ['3' 2.0 1.0 ... 3 1 1315]
 ['3.9' 1.0 1.0 ... 4 2 575]]


In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y, test_size=0.2,random_state=1)


In [19]:
print(X_train)

[['3.3' 2.0 1.0 ... 4 1 1315]
 ['3.7' 1.0 1.0 ... 4 2 1315]
 ['3.6' 2.0 1.0 ... 4 2 900]
 ...
 ['3.4' 2.0 1.0 ... 3 2 575]
 ['3.8' 1.0 1.0 ... 4 2 900]
 ['3.4' 1.0 1.0 ... 4 2 1315]]


In [18]:
print(X_test)

[['2.71' 2.0 2.0 ... 4 2 760]
 ['3.605' 1.0 1.0 ... 5 2 900]
 ['3.5' 2.0 2.0 ... 5 1 760]
 ...
 ['3.7' 1.0 1.0 ... 3 2 900]
 ['3.8' 2.0 1.0 ... 5 1 1315]
 ['3.68' 2.0 1.0 ... 4 1 1315]]


In [20]:
print(y_train)

['185' '127' '170' '184' '135' '168' '130' '135' '165' '135' '113' '192'
 '165' '170' '200' '116' '155' nan '170' '150' '165' '135' '175' '150'
 '155' '175' '200' '190' '175' '140' '129' '144 lbs' '135' '185' '150'
 '130' '170' '190' '140' '180' '120' '200' '160' '100' '105' '185' '170'
 '210' '150' '195' '140' 'Not sure, 240' '129' '115' '180' '145' '165'
 '180' '190' '135' '187' '138' '140' '185' '118' '180' '137' '156' '123'
 '190' '175' '155' '155' '145' '128' '185' '167' '180' '110' '167' '135'
 '160' '175' '169' '125' '180' '200' '140' '150' '155' '145' '140' '145'
 '190' '120' '125' '140' '264' '165' '170']


In [21]:
print(y_test)

[nan '113' '155' '205' '112' '125' '140' '125' '150' '128' '210' '170'
 '125' '230' '185' '130' '150' '130' '120' "I'm not answering this. "
 '265' '135' '160' '175' '260']


In [24]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
X=np.array(ct.fit_transform(X))

In [25]:
print(X)

[[1.0 0.0 0.0 ... 5 1 1315]
 [1.0 0.0 0.0 ... 4 2 900]
 [1.0 0.0 0.0 ... 5 1 900]
 ...
 [1.0 0.0 0.0 ... 4 2 1315]
 [1.0 0.0 0.0 ... 3 1 1315]
 [1.0 0.0 0.0 ... 4 2 575]]


In [26]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [27]:
print(y)

[34 22 45 46 35 35 31 16 31 10  6  2 43  9 33 31 20 29 15 25 30 37 33 33
  1 10 24 30 31 26  5 39 47 12 21 21 21 29 21 30 18  8 15  0 29  4 27 20
 22 21 28 33 38 44 25 36 30 18 22 22 15  7 40 31 18  3 10 19 20 14 18 18
 18 38 47  8 21 38 15 20 14 35 29 11 26 18 35 22 30 13 42 15 35 25 30 32
 40 22 33 25 10 24 15 14 41 10 14 25 12 38 24 29 13 29 17 21 29  4 18 33
 23 31  8 15 15]


In [31]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train = sc.fit_transform(X_train)
X_test=sc.transform(X_test)


ValueError: ignored

In [32]:
print(X_train)


[['3.3' 2.0 1.0 ... 4 1 1315]
 ['3.7' 1.0 1.0 ... 4 2 1315]
 ['3.6' 2.0 1.0 ... 4 2 900]
 ...
 ['3.4' 2.0 1.0 ... 3 2 575]
 ['3.8' 1.0 1.0 ... 4 2 900]
 ['3.4' 1.0 1.0 ... 4 2 1315]]


In [33]:
print(X_test)

[['2.71' 2.0 2.0 ... 4 2 760]
 ['3.605' 1.0 1.0 ... 5 2 900]
 ['3.5' 2.0 2.0 ... 5 1 760]
 ...
 ['3.7' 1.0 1.0 ... 3 2 900]
 ['3.8' 2.0 1.0 ... 5 1 1315]
 ['3.68' 2.0 1.0 ... 4 1 1315]]
